#!/usr/bin/env python3
# Write a script to generate two different reports based on the ranking of errors generated by the system and the user usage statistics for the service

import csv
import pandas
import regex as re
path = 'Python-main\src\package_klova9\Practice\Lab6\syslog.log'
key = []
value = []
name = []
per_user = dict(key = key, value = value, name = name)
error = dict(key = key, value = value, name = name)
with open(path) as f:
    for line in f.readlines():
        
        try:
            k = re.search("\w+\s\d+\s\d+\:\d+\:\d+", line).group(0)
        except:
            k = re.search("\w+\s\d+\s\d+\:\d+\:\d+", line)
        v = re.search("ERROR|INFO.+[(]|[[]", line).group(0)
        n = re.search("\(([^)]+)\)", line).group(1)
        v = re.sub(r'\W', '', v)
        if v.find('ERROR') == True:
            error.update(v).append(v)
        elif v.find('INFO')== True:
            per_user[value].append(v)
        else: per_user[value].append(k)
        key.append(k)
        name.append(n)
f.close()
header = ['key', 'value', 'name']
df = pandas.DataFrame(per_user)
df.to_csv(r'Python-main\src\package_klova9\Practice\Lab6\user_log.csv')

    


